version: "3.3"
services:
  api:
    container_name: courier-api
    image: node:14-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: npm run start:${ENV:-"prod"}
    ports:
      - "3000:3000"
    restart: on-failure
